# Generated by Django 3.0.8 on 2020-07-13 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='djangoclasses',
            old_name='instructor_number',
            new_name='instructor_name',
        ),
    ]
